# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 16/6 * * *'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update CSV
      run: |
        python update_stats.py
        git diff
        git config --global user.email "duanxianpi@gmail.com"
        git config --global user.name "duanxianpi"
        git add stats.csv
        git commit -m "Github Action Auto Updated"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
